# Stage 1: Build
FROM node:latest AS builder

WORKDIR /app

# Install dependencies first (better caching)
COPY package*.json ./
RUN npm install

# Copy source and build
COPY . .
RUN npm run build

# Stage 2: Runtime
FROM node:latest

WORKDIR /app

# Copy built output from builder stage
# Nuxt 3 builds to the .output directory
COPY --from=builder /app/.output ./.output

# Optional: If you need runtime environment variables
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

# Start the server using the entry point generated by Nitro
CMD ["node", ".output/server/index.mjs"]
